### PR TITLE
Bugfixes for using leatherman as a standalone installed library

### PR DESCRIPTION
**Pull request by adrienthebo**
The official recommendation from @branan is to install leatherman to the system and build from there, but some testing logic was assuming that leatherman was being used as a vendor library and some cmake files weren't being installed to system locations. This pull request fixes the needful.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I suspect you're not using some of the libraries, as I think Ruby has the same problem with test files.

**Comment by branan** [comment]
`add_leatherman_test` shouldn't need to be wrapped, since it just exports a variable (which will be unused in the `find_package` case)

When `add_library` or `add_executable` is explicitly called it does need to be wrapped, since those source files obviously won't exist in an installed Leatherman.It might be worth adding macros for this, but I don't expect us to be writing lots more code that requires fixture libraries/executables (*most* mocking/stubbing can be done without the need for an extra library, and obviously dynamic_library and execution are special in their testing needs)

**Comment by MikaelSmith** [comment]
Oh right. I'd kind of prefer pulling the `add_leatherman_test` sections out so we don't have more confusion about why it's inconsistent.

**Comment by branan** [comment]
Yeah, I agree. Let's only move what we need to into conditionals. It's cleaner, and it'll help us see what we might want to add helpers for in the future

**Comment by adrienthebo** [comment]
Okay, moved the `add_leatherman_test` statements outside of the conditionals.

**Comment by MikaelSmith** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Nitpick, can you add `(maint)` prefixes to the commits?

**Comment by adrienthebo** [comment]
Commit messages fixed up.

**Comment by MikaelSmith** [comment]
Thanks.

**Pull request merged**
