### PR TITLE
(LTH-66) Update CHANGELOG for 0.3.0

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by branan** [comment]
Is there any reason this has been sitting around besides churn around releases? I'm happy to hit the button at this point

**Comment by MikaelSmith** [comment]
Not that I'm aware of. I was undecided and using LTH ticket numbers for changes that have them.

**Comment by whopper** [comment]
@MikaelSmith :+1: would now be a good time to hit the button?

**Comment by MikaelSmith** [comment]
We can leave this open until we tag a version. Likely to happen when @branan's done setting up Github archives.

**Comment by MikaelSmith** [comment]
Once this goes in, we'll tag the 0.3.0 release.

**Comment by branan** [comment]
:+1:

**Pull request merged**
