### PR TITLE
(maint) Switch to using compressed vendored packages

### PR DESCRIPTION
**Pull request by MikaelSmith**
Switches to using compressed vendored packages to make git history less
noisy when changing versions. Also simplify CMake files for vendored
libraries with a new macro.

Split into two commits so they're easier to review.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This may have a side-effect of giving us more honest coverage numbers. I think rapidjson, nowide, and catch were probably pretty well covered by unit tests.

**Comment by MikaelSmith** [comment]
Oh right, compiling a library is a problem with this pattern. Only works for header-only libraries.

**Comment by MikaelSmith** [comment]
Probably needs some work to get dependencies right.

**Comment by MikaelSmith** [comment]
@branan thoughts on this idea?

**Comment by ahenroid** [comment]
This sounds like a great idea. Is there no way to apply this also to compiled libraries?

**Comment by MikaelSmith** [comment]
@ahenroid extracting the packages happens during a build, not CMake configuration, and CMake doesn't make a special case for dependencies. CMake will fail to identify the right build order and in fact will error because the source file we want to build isn't available yet.

**Comment by MikaelSmith** [comment]
I'm not sure coveralls data is being uploaded correctly :( looking into it.

**Comment by MikaelSmith** [comment]
Fixed code coverage flags.

**Comment by MikaelSmith** [comment]
This could switch to using git-lfs...

**Comment by kylog** [comment]
After hipchatter everyone was thumbs-up on this.

**Pull request merged**
