### PR TITLE
(packaging) Add project version to libraries

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds the version number to Leatherman libs. That causes a version of
the libraries with the version number appended to be built on many
platforms, and on Windows adds build metadata specifying the version.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@branan any objection to this?

**Comment by branan** [comment]
I'm +1 to versioned .so files, generally.

Is there additional work we need to do to ensure that our executables will be correctly linked to the versioned .so, or does CMake handle that for us with their target import/export stuff?

**Comment by MikaelSmith** [comment]
I think it'll handle it, but I'm not sure. Probably worth a pass through Windows and Linux packaging builds to see if anything unexpected happens.

**Comment by MikaelSmith** [comment]
On Linux, it does seem to resolve to the versioned libraries
```
[root@r98dsr9hiaofxd9 lib]# ldd libfacter.so
	linux-vdso.so.1 =>  (0x00007fffad9d8000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f390bc04000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f390b9fb000)
	leatherman_curl.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_curl.so.0.7.5 (0x00007f390b790000)
	leatherman_ruby.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_ruby.so.0.7.5 (0x00007f390b515000)
	leatherman_execution.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_execution.so.0.7.5 (0x00007f390b28c000)
	leatherman_dynamic_library.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_dynamic_library.so.0.7.5 (0x00007f390b02a000)
	leatherman_file_util.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_file_util.so.0.7.5 (0x00007f390adb4000)
	leatherman_util.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_util.so.0.7.5 (0x00007f390aa80000)
	leatherman_logging.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_logging.so.0.7.5 (0x00007f390a7a3000)
	leatherman_locale.so.0.7.5 => /opt/puppetlabs/puppet/lib/leatherman_locale.so.0.7.5 (0x00007f390a404000)
	libcrypto.so.1.0.0 => /opt/puppetlabs/puppet/lib/libcrypto.so.1.0.0 (0x00007f390a026000)
	libcurl.so.4 => /opt/puppetlabs/puppet/lib/libcurl.so.4 (0x00007f3909dc3000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3909ac1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f39098a4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f39094e3000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f39092de000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f390c217000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f39090d9000)
	libssl.so.1.0.0 => /opt/puppetlabs/puppet/lib/libssl.so.1.0.0 (0x00007f3908e6d000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f3908c56000)
```

**Pull request merged**
