### PR TITLE
(LTH-7) Fix LEATHERMAN_LIBRARIES ordering

### PR DESCRIPTION
**Pull request by MikaelSmith**
Without this change, Windows release builds use debug libraries because
the optimized/debug labeling CMake adds in the LIBS variables gets
reversed. Insert libraries in reverse order rather than reversing at the
end so we get the labels in the correct order.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Looks like I might need to ensure libs don't end up in deps.

**Comment by MikaelSmith** [comment]
Fixed and verified in Facter.

**Comment by branan** [comment]
This looks more correct than the old version to me, and "works on my laptop". Let's see what happens

**Pull request merged**
