### PR TITLE
(maint) Add execute permissions on Windows test fixture

### PR DESCRIPTION
**Pull request by MikaelSmith**
On Windows running inside Cygwin, the test using error_message.bat fails
due to lack of execute permissions. Add the execute bit on batch files
so tests will run successfully within Cygwin.

### CODE REVIEW

**Comment by melissa** [comment]
:+1: works with my testing on vanagon!!

**Comment by jcoconnor** [comment]
Sensible change :+1:

**Comment by melissa** [comment]
Thanks all!

**Comment by melissa** [comment]
What do we have to do to get this released and promoted into https://github.com/puppetlabs/puppet-agent/blob/master/configs/components/leatherman.json#L1 ?

**Comment by MikaelSmith** [comment]
I'll put together some release notes.

**Pull request merged**
