### PR TITLE
(maint) Allow consuming projects to know if we have locale support

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Consuming projects still have to set LEATHERMAN_USE_LOCALES?

**Comment by branan** [comment]
@MikaelSmith I'm happy to make it all fully automagical based on `LEATHERMAN_HAVE_LOCALE`, but I thought it'd be useful to still let applications turn off their use of locales if they wanted

**Comment by MikaelSmith** [comment]
Ok, I'll go with that for now.

**Comment by MikaelSmith** [comment]
Branch for test builds at https://github.com/MikaelSmith/puppet-agent/tree/test-locale.

**Comment by MikaelSmith** [comment]
:+1:

**Pull request merged**
