### PR TITLE
(maint) Add get_commit_string helper

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds a get_commit_string helper for getting a commit description string
in CMake.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This should be followed with an update to Facter to use it.

**Comment by branan** [comment]
This one's going to take a bit more review than the others :)

I'll start reading through it

**Comment by MikaelSmith** [comment]
This is pulled from https://github.com/puppetlabs/facter/blob/master/lib/CMakeLists.txt#L8-L16; I found we didn't use the SHA1 result, just LIBFACTER_COMMIT.

**Comment by branan** [comment]
Sweet, good to know this isn't whole-cloth :)

**Comment by branan** [comment]
These are inconsistently named - `git_describe` `git_get_exact_tag` and `get_git_head_revision`. I know some of that comes from git, but would be nice to normalize our interface to the git info we want

**Comment by MikaelSmith** [comment]
Those all come from a 3rd party script we've adopted. We could update them, but I'm not sure it's worth the inconsistency with the original.

**Pull request merged**
