### PR TITLE
(maint) Renamed types to use CamelCase throughout

### PR DESCRIPTION
**Pull request by Magisus**
I changed all the ones I could find, if any one sees any that I missed I'll add them. 

Once we merge this, most of the projects that use Leatherman will need updating to reflect the rename.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Definitely brings a contrast to the stl and boost names.

**Comment by Magisus** [comment]
There's still time to go the other way... :P

**Comment by peterhuene** [comment]
I'm not a fan :/ but ¯\_(ツ)_/¯

**Comment by MikaelSmith** [comment]
I'm finding I have a stronger opinion about it than I thought.

**Comment by Magisus** [comment]
Michael's argument about STL and Boost is pretty strong within the context of Leatherman specifically, since it is designed to be used a lot like those libraries, as a "3rd party" set of utilities. Whether or not the various teams change things in their respective projects, Leatherman needs to be internally consistent. Which means no matter what we do, someone is going to cringe whenever they use it, and it's going to look weird with their code. 

So the question is, who gets to cringe and who gets to enjoy seamless meshing? In terms of the projects that want to integrate Leatherman, is there one where we care about consistency more for any reason?

**Comment by ploubser** [comment]
Since there are such strong opinions about this, let's just go with the suggested STL/Boost style.

Our team will make the changes to our projects over time.

**Pull request closed without merging**
