### PR TITLE
(maint) Add support for static Boost with ICU

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
Backport of fix https://github.com/puppetlabs/leatherman/commit/38b31eff75f01e810eab0b3f05d04c5665fa722c (originally landed in master)

Pulls in the FindICU module from
https://github.com/julp/FindICU.cmake#6fc73154d70b6611027f5475296386c3e66851af

Enabled by setting LEATHERMAN_USE_ICU.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Which branch should it be targeted at?

**Comment by McdonaldSeanp** [comment]
@MikaelSmith the oldest one we can target it for

**Comment by McdonaldSeanp** [comment]
Oh, crap

it's not targeted at the right onw

**Comment by McdonaldSeanp** [comment]
@MikaelSmith updated to target 0.12

**Pull request merged**
