### PR TITLE
(LTH-52) Remove use of MemoryPoolAllocator

### PR DESCRIPTION
**Pull request by MikaelSmith**
The MemoryPoolAllocator is buggy on Solaris SPARC, and hasn't been shown
to constitute a significant performance benefit for our use. Switch to
using plain CrtAllocator.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This follows a typedef pattern established in FACT-1240.

**Comment by MikaelSmith** [comment]
I'm hopeful this fixes things.

**Comment by peterhuene** [comment]
:+1:

**Comment by peterhuene** [comment]
From a cursory glance, the following members need review for needlessly copying vectors:

```c++
std::string toString(std::vector<JsonContainerKey> keys) const;
size_t size(std::vector<JsonContainerKey> keys) const;
bool includes(std::vector<JsonContainerKey> keys) const;
DataType type(std::vector<JsonContainerKey> keys) const;
DataType type(std::vector<JsonContainerKey> keys, const size_t idx) const;
T get(std::vector<JsonContainerKey> keys) const;
T get(std::vector<JsonContainerKey> keys, const size_t idx) const;
T getWithDefault(std::vector<JsonContainerKey> keys, const T& default_value) const;
void set(std::vector<JsonContainerKey> keys, T value);
json_value* getValueInJson(std::vector<JsonContainerKey> keys, const bool is_array,const size_t idx) const;
```

**Pull request merged**
